In [33]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [34]:
file_name = 'KeyPressEvent'
df = pd.read_csv('../Our Data Windowed/' + file_name + '.csv')

In [35]:
df = df[df.WindowNumber != -1]

In [20]:
def get_deltas(df):
    deltas = []
    ultimo0 = 0
    ultimo1 = 0
    found0 = False
    found1 = False
    for _,row in df.iterrows():
        currentSystime = row.Systime
        if row.PressType == 0:
            if found1:
                deltas.append(currentSystime-ultimo1)
            else:
                deltas.append(None)
            ultimo0 = currentSystime
            found0 = True
        elif row.PressType == 1:
            if found0:
                deltas.append(currentSystime-ultimo0)
            else:
                deltas.append(None)
            ultimo1 = currentSystime
            found1 = True
    return deltas

In [21]:
aux = []
for session in df.SessionID.unique():
    aux += get_deltas(df[df.SessionID == session])
    print(session)
df['Deltas'] = aux

Jo1
Diego01
Toto8
Toto1
Toto6
Toto7
Toto9
jo3
jo4
jo2
Diego02
Diego03
Diego04
Toto5
Toto2
Andres1

In [22]:
df

,Systime,PressTime,PressType,ActivityID,KeyID,Phone_orientation,SessionID,WindowNumber,Deltas
0,1537190598209,NaN,0,Jo1,-1,0,Jo1,NaN,NaN
1,1537190598267,NaN,1,Jo1,-1,0,Jo1,0.0,58.0
2,1537190598667,NaN,0,Jo1,101,0,Jo1,0.0,400.0
3,1537190598757,NaN,1,Jo1,101,0,Jo1,0.0,90.0
4,1537190598822,NaN,0,Jo1,117,0,Jo1,0.0,65.0
5,1537190598935,NaN,1,Jo1,117,0,Jo1,0.0,113.0
6,1537190599224,NaN,0,Jo1,98,0,Jo1,0.0,289.0
7,1537190599322,NaN,1,Jo1,98,0,Jo1,0.0,98.0
8,1537190599545,NaN,0,Jo1,112,0,Jo1,0.0,223.0
9,1537190599674,NaN,1,Jo1,112,0,Jo1,0.0,129.0
10,1537190599712,NaN,0,Jo1,114,0,Jo1,0.0,38.0
11,1537190599778,NaN,1,Jo1,114,0,Jo1,0.0,66.0
12,1537190600083,NaN,0,Jo1,111,0,Jo1,0.0,305.0
13,1537190600151,NaN,1,Jo1,111,0,Jo1,0.0,68.0
14,1537190600887,NaN,0,Jo1,-5,0,Jo1,0.0,736.0
15,1537190600897,NaN,1,Jo1,-5,0,Jo1,0.0,10.0
16,1537190601043,NaN,0,Jo1,-5,0,Jo1,0.0,146.0
17,1537190601052,NaN,1,Jo1,-5,0,Jo1,0.0,9.0
18,1537190601192,NaN,0,Jo1,-5,0,Jo1,0.0,140.0
19,1537190601201,NaN,1,Jo1,-5,0,Jo1,0.0,9.0
20,1537190601337,NaN,0,Jo1,-5,0,Jo1,0.0,136.0
21,1537190601346,NaN,1,Jo1,-5,0,Jo1,0.0,9.0
22,1537190601503,NaN,0,Jo1,-5,0,Jo1,0.0,157.0
23,1537190601512,NaN,1,Jo1,-5,0,Jo1,0.0,9.0
24,1537190601939,NaN,0,Jo1,-1,0,Jo1,0.0,427.0
25,1537190602018,NaN,1,Jo1,-1,0,Jo1,0.0,79.0
26,1537190602377,NaN,0,Jo1,117,0,Jo1,0.0,359.0
27,1537190602462,NaN,1,Jo1,117,0,Jo1,0.0,85.0
28,1537190602830,NaN,0,Jo1,32,0,Jo1,0.0,368.0
29,1537190602839,NaN,1,Jo1,32,0,Jo1,0.0,9.0
...,...,...,...,...,...,...,...,...,...
41573,1541942069442,NaN,0,Andres1,113,0,Andres1,54.0,749.0
41574,1541942069514,NaN,1,Andres1,113,0,Andres1,54.0,72.0
41575,1541942070045,NaN,0,Andres1,117,0,Andres1,54.0,531.0
41576,1541942070119,NaN,1,Andres1,117,0,Andres1,54.0,74.0
41577,1541942070259,NaN,0,Andres1,105,0,Andres1,54.0,140.0
41578,1541942070357,NaN,1,Andres1,105,0,Andres1,54.0,98.0
41579,1541942070996,NaN,0,Andres1,32,0,Andres1,54.0,639.0
41580,1541942071003,NaN,1,Andres1,32,0,Andres1,54.0,7.0
41581,1541942071415,NaN,0,Andres1,110,0,Andres1,54.0,412.0
41582,1541942071499,NaN,1,Andres1,110,0,Andres1,54.0,84.0
41583,1541942071728,NaN,0,Andres1,111,0,Andres1,54.0,229.0
41584,1541942071831,NaN,1,Andres1,111,0,Andres1,54.0,103.0
41585,1541942077477,NaN,0,Andres1,-5,0,Andres1,NaN,5646.0
41586,1541942077482,NaN,1,Andres1,-5,0,Andres1,NaN,5.0
41587,1541942077710,NaN,0,Andres1,-5,0,Andres1,NaN,228.0
41588,1541942077715,NaN,1,Andres1,-5,0,Andres1,NaN,5.0
41589,1541942077906,NaN,0,Andres1,-5,0,Andres1,NaN,191.0
41590,1541942077910,NaN,1,Andres1,-5,0,Andres1,NaN,4.0
41591,1541942078121,NaN,0,Andres1,-5,0,Andres1,NaN,211.0
41592,1541942078127,NaN,1,Andres1,-5,0,Andres1,NaN,6.0
41593,1541942078320,NaN,0,Andres1,-5,0,Andres1,NaN,193.0
41594,1541942078326,NaN,1,Andres1,-5,0,Andres1,NaN,6.0
41595,1541942078541,NaN,0,Andres1,-5,0,Andres1,NaN,215.0
41596,1541942078546,NaN,1,Andres1,-5,0,Andres1,NaN,5.0
41597,1541942078756,NaN,0,Andres1,-5,0,Andres1,NaN,210.0
41598,1541942078761,NaN,1,Andres1,-5,0,Andres1,NaN,5.0
41599,1541942079005,NaN,0,Andres1,-5,0,Andres1,NaN,244.0
41600,1541942079010,NaN,1,Andres1,-5,0,Andres1,NaN,5.0
41601,1541942080965,NaN,0,Andres1,-3,0,Andres1,NaN,1955.0
41602,1541942081037,NaN,1,Andres1,-3,0,Andres1,NaN,72.0

In [23]:
def getPressTypeDelta(x):
    print(x == 1)

In [24]:
grouped_df = df.groupby(['SessionID', 'WindowNumber']).agg({
    'PressType': {
        'Press_count': lambda x: x.count(),
    }
})

/Users/thicorfon/anaconda3/lib/python3.6/site-packages/pandas/core/groupby.py:4291: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)

In [25]:
filteredByPressType1 = df[df.PressType == 1].copy()
filteredByPressType0 = df[df.PressType == 0].copy()

In [26]:
grouped0_df = filteredByPressType0.groupby(['SessionID', 'WindowNumber']).agg({
    'Deltas': {
        'Deltas_0_mean': 'mean',
        'Deltas_0_median': 'median',
        'Deltas_0_std': 'std'
    }
})

/Users/thicorfon/anaconda3/lib/python3.6/site-packages/pandas/core/groupby.py:4291: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)

In [27]:
grouped1_df = filteredByPressType1.groupby(['SessionID', 'WindowNumber']).agg({
    'Deltas': {
        'Deltas_1_mean': 'mean',
        'Deltas_1_median': 'median',
        'Deltas_1_std': 'std'
    }
})

/Users/thicorfon/anaconda3/lib/python3.6/site-packages/pandas/core/groupby.py:4291: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)

In [28]:
features = grouped_df.merge(grouped0_df, left_index=True, right_index=True).merge(grouped1_df, left_index=True, right_index=True)

In [29]:
features.columns = features.columns.droplevel()

In [30]:
features = features.reset_index()

In [31]:
features

,SessionID,WindowNumber,Press_count,Deltas_0_mean,Deltas_0_median,Deltas_0_std,Deltas_1_mean,Deltas_1_median,Deltas_1_std
0,Andres1,0.0,5,585.000000,585.0,65.053824,68.666667,68.0,8.020806
1,Andres1,1.0,16,2251.000000,722.0,4283.073429,66.000000,70.0,28.480570
2,Andres1,2.0,26,639.076923,539.0,439.608246,122.153846,87.0,191.819727
3,Andres1,3.0,7,2486.000000,465.5,4206.432614,59.000000,82.0,43.347434
4,Andres1,4.0,38,462.631579,334.0,398.472669,66.736842,76.0,26.339329
5,Andres1,5.0,37,478.777778,396.0,256.692894,68.894737,82.0,33.125845
6,Andres1,6.0,28,624.142857,597.0,447.708500,51.785714,67.0,30.143703
7,Andres1,7.0,32,598.812500,426.0,345.488682,64.875000,69.0,36.877952
8,Andres1,8.0,30,406.733333,418.0,197.948935,61.400000,66.0,25.762098
9,Andres1,12.0,6,14257.666667,943.0,23502.121231,62.000000,63.0,10.535654
10,Andres1,13.0,22,821.272727,467.0,709.976632,60.454545,64.0,32.309019
11,Andres1,14.0,42,423.095238,339.0,250.763814,62.619048,75.0,34.937768
12,Andres1,15.0,28,652.214286,457.5,543.551311,53.000000,72.0,37.849906
13,Andres1,16.0,18,549.666667,203.0,602.912514,19.333333,6.0,27.581697
14,Andres1,19.0,12,5604.333333,507.5,12532.134769,59.166667,61.5,27.859768
15,Andres1,20.0,32,634.625000,474.5,444.386150,35.625000,28.5,32.109967
16,Andres1,21.0,22,705.636364,442.0,865.157011,72.272727,78.0,40.939201
17,Andres1,25.0,28,2939.642857,419.5,9199.885155,48.928571,69.0,39.713327
18,Andres1,26.0,14,753.857143,790.0,301.935108,66.714286,74.0,30.928489
19,Andres1,27.0,18,1471.888889,398.0,3212.027998,66.111111,65.0,26.107683
20,Andres1,28.0,32,581.750000,424.0,428.066739,65.250000,70.0,25.823762
21,Andres1,29.0,30,577.400000,434.0,336.887179,66.933333,67.0,25.641670
22,Andres1,30.0,12,1648.333333,1543.0,1292.135235,56.833333,70.0,41.791945
23,Andres1,31.0,24,779.333333,464.0,661.978211,62.833333,71.5,31.103444
24,Andres1,33.0,20,1697.700000,317.0,3271.134395,64.200000,64.5,9.852242
25,Andres1,34.0,52,416.346154,218.5,511.843565,37.538462,6.0,38.957650
26,Andres1,35.0,32,573.750000,405.0,496.736080,66.812500,73.0,34.170589
27,Andres1,36.0,18,783.666667,300.0,857.252880,39.111111,6.0,40.513715
28,Andres1,37.0,22,874.454545,527.0,935.210496,66.818182,80.0,42.385890
29,Andres1,39.0,22,1982.181818,385.0,5186.397609,67.818182,73.0,34.876405
...,...,...,...,...,...,...,...,...,...
516,jo4,6.0,86,163.860465,131.0,118.132408,68.930233,75.0,31.648663
517,jo4,7.0,68,248.852941,193.0,215.634389,51.058824,61.5,41.314713
518,jo4,8.0,84,168.047619,155.0,97.503709,67.285714,76.5,34.231839
519,jo4,9.0,85,170.697674,140.0,124.135781,65.071429,82.5,36.859253
520,jo4,10.0,39,452.473684,156.0,877.227031,69.550000,76.5,30.116397
521,jo4,11.0,74,179.027027,158.0,123.933559,68.675676,75.0,35.356953
522,jo4,12.0,57,354.620690,157.0,411.872589,48.892857,37.0,47.532709
523,jo4,13.0,96,162.312500,139.5,113.009538,52.625000,65.5,35.058386
524,jo4,14.0,94,152.978723,135.0,119.296578,58.765957,71.0,39.297756
525,jo4,15.0,94,144.978723,124.0,125.731856,63.638298,74.0,42.477322
526,jo4,16.0,84,212.235294,141.0,214.151894,320.640000,84.0,409.435239
527,jo4,17.0,87,167.883721,150.0,117.165371,58.659091,72.5,36.011589
528,jo4,18.0,107,127.000000,108.5,89.997065,63.320755,72.0,32.859124
529,jo4,19.0,59,288.103448,201.0,502.524224,56.100000,66.0,39.844828
530,jo4,20.0,51,317.846154,158.0,388.951276,70.080000,81.0,37.601995
531,jo4,21.0,89,156.818182,125.5,159.962244,68.022222,81.0,38.938465
532,jo4,22.0,47,345.166667,156.5,885.445634,75.130435,79.0,36.869924
533,jo4,23.0,77,196.315789,121.5,251.234154,63.205128,74.0,34.757945
534,jo4,24.0,76,200.105263,139.5,179.127282,64.789474,69.0,36.689462
535,jo4,25.0,92,141.086957,131.0,89.132318,62.521739,74.5,39.274951
536,jo4,26.0,24,858.916667,152.0,1855.770629,30.000000,4.0,39.168633
537,jo4,27.0,74,211.162162,148.0,226.289823,55.486486,71.0,38.725258
538,jo4,28.0,84,165.714286,124.5,174.867097,62.047619,75.0,36.337814
539,jo4,29.0,87,179.750000,139.5,204.844482,60.302326,82.0,39.353426
540,jo4,30.0,71,213.685714,136.0,288.334953,69.416667,82.0,43.093503
541,jo4,31.0,78,207.000000,157.0,174.402438,46.615385,53.0,38.965312
542,jo4,32.0,79,192.375000,142.0,164.270366,63.358974,70.0,29.458702
543,jo4,33.0,42,541.761905,206.0,752.683327,41.095238,35.0,32.418983
544,jo4,34.0,81,183.658537,144.0,165.885142,64.725000,79.0,36.537292
545,jo4,35.0,78,186.025641,108.0,208.329002,68.410256,74.0,46.548626

In [32]:
features.to_csv('../Our Data Features/'+file_name+ '_mean_std.csv', index=False)